server:
  port: 8084
spring:
  application:
    name: prueba
  datasource:
    url: jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
